### ISSUE TITLE
Wrong color codes for India.

### ISSUE THREAD

**Issue by indyaah** [reimertz/flag-colors#3]
First of all great work compiling all the flag colors. The color codes for Indian flag are completely off. 
I am going to open up a PR after fixing the codes. Hope that's ok.

**Comment by reimertz** [comment]
@indyaah Yeah, that would be awesome!

Would it be to much to ask that you implement functionality that  that override the colors I fetch from http://www.crwflags.com ?

**Comment by reimertz** [comment]
You can follow the code from here: https://github.com/reimertz/flag-colors/blob/master/gulptasks/fetchFlagColors.js#L85

Because at the moment, what I do is to fetch all flags from there, then use ImageMagick to get color palettes for each flag, and then store them in flagColors.json. 

If we would start to edit the json file, the next fetch I do would overwrite all manual changes to that file. 

Does this make sense?

**Comment by reimertz** [comment]
@indyaah actually, ignore my previous rant. It seems the source im using is very dated. I will update it to use https://en.wikipedia.org/wiki/Gallery_of_sovereign_state_flags instead. 

Thanks again!

**Comment by reimertz** [comment]
@indyaah I swapped to using wikipedia.org as a source instead, so all colors should be fine now. thanks again for pointing this issue out. Added a lot of legibility. <3

**Comment by indyaah** [comment]
@reimertz : Cool. And apologies I missed all the comments for about 2 hours. :+1:
